/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Cobranzas;

import java.util.List;
import Models.Credito;
import Models.Carton;
import Models.Cliente;
import Models.Comercio;
import Models.Empleado;
import DAO.CreditosDAO;
import Statics.Funciones;
import java.sql.Timestamp;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hernan
 */
public class GeneracionCartones extends javax.swing.JPanel {

    /**
     * Creates new form GeneracionCartones
     */
    private List <Credito> listaCreditos;
    private CreditosDAO creditosDao;
    private Credito creditoSelected;
    private boolean cartonGenerado;

    public GeneracionCartones() {
        initComponents();
        creditosDao=CreditosDAO.getInstance();
        cartonGenerado=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabla_Solicitudes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabelCreditoNumero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCantCuotas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelImportCuota = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPlanSeleccionado = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelNumCreditoUnificado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelImporteCredito = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_vendedor = new javax.swing.JLabel();
        lbl_cobrador = new javax.swing.JLabel();
        lbl_administrador = new javax.swing.JLabel();
        lbl_gerente = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lbl_fechaAprobacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaObservacionesCredito = new javax.swing.JTextArea();
        jButtonGenerar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelUltimaCuota = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelFechaInicioCobro = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelCobrador = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jButtonImprimirCarton = new javax.swing.JButton();

        jLabel1.setText("Creditos pendientes para generar cuotas y cartones del sistema:");

        tabla_Solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Titular", "Cobrador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_Solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_SolicitudesMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabla_Solicitudes);
        if (tabla_Solicitudes.getColumnModel().getColumnCount() > 0) {
            tabla_Solicitudes.getColumnModel().getColumn(0).setResizable(false);
            tabla_Solicitudes.getColumnModel().getColumn(0).setPreferredWidth(2);
            tabla_Solicitudes.getColumnModel().getColumn(1).setResizable(false);
            tabla_Solicitudes.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabla_Solicitudes.getColumnModel().getColumn(2).setResizable(false);
            tabla_Solicitudes.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        jLabel2.setText("Credito Nº");

        jLabelCreditoNumero.setText("123");

        jLabel4.setText("Cant Cuotas:");

        jLabelCantCuotas.setText("123");

        jLabel6.setText("Importe Cuota");

        jLabelImportCuota.setText("$$");

        jLabel8.setText("Ultima Cuota");

        jLabel9.setText("Plan seleccionado");

        jLabelPlanSeleccionado.setText("xPlan");

        jLabel11.setText("Unifcado con Nº");

        jLabelNumCreditoUnificado.setText("123");

        jLabel13.setText("Importe del credito:");

        jLabelImporteCredito.setText("$$");

        jLabel16.setText("Observaciones del credito:");

        jLabel23.setText("Gerente:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42.setText("Aprobaciones del personal:");

        jLabel25.setText("Cobrador:");

        jLabel26.setText("Administrador:");

        jLabel24.setText("Vendedor:");

        lbl_vendedor.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_vendedor.setText("Nombre de la persona que aprobo");

        lbl_cobrador.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_cobrador.setText("Nombre de la persona que aprobo");

        lbl_administrador.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_administrador.setText("Nombre de la persona que aprobo");

        lbl_gerente.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_gerente.setText("Nombre de la persona que aprobo");

        jLabel43.setText("Fecha aprobación:");

        lbl_fechaAprobacion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lbl_fechaAprobacion.setText("1/1/1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fechaAprobacion)
                            .addComponent(lbl_gerente)
                            .addComponent(lbl_administrador)
                            .addComponent(lbl_cobrador)
                            .addComponent(lbl_vendedor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lbl_cobrador))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(lbl_administrador))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(lbl_gerente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(lbl_fechaAprobacion)))
                    .addComponent(lbl_vendedor, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTextAreaObservacionesCredito.setColumns(20);
        jTextAreaObservacionesCredito.setRows(5);
        jScrollPane1.setViewportView(jTextAreaObservacionesCredito);

        jButtonGenerar.setText("Generar cuotas");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar/Limpiar Seleccion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelUltimaCuota.setText("_/_/_");

        jLabel15.setText("Fecha de inicio cobranza:");

        jLabelFechaInicioCobro.setText("_/_/_");

        jLabel19.setText("Cobrador:");

        jLabelCobrador.setText("algun");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonImprimirCarton.setText("Imprimir Carton");
        jButtonImprimirCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirCartonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel15)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel8)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUltimaCuota)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCreditoNumero)
                                            .addComponent(jLabelPlanSeleccionado))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelFechaInicioCobro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCantCuotas)
                                            .addComponent(jLabelNumCreditoUnificado))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13))
                                        .addGap(61, 61, 61)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelImportCuota)
                                            .addComponent(jLabelImporteCredito)))
                                    .addComponent(jLabelCobrador))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel16))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jButton2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonImprimirCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(84, 84, 84)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80)
                                .addComponent(jButtonBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelCreditoNumero)
                            .addComponent(jLabel4)
                            .addComponent(jLabelCantCuotas)
                            .addComponent(jLabel6)
                            .addComponent(jLabelImportCuota))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabelPlanSeleccionado)
                            .addComponent(jLabel11)
                            .addComponent(jLabelNumCreditoUnificado)
                            .addComponent(jLabel13)
                            .addComponent(jLabelImporteCredito))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabelFechaInicioCobro)
                            .addComponent(jLabel19)
                            .addComponent(jLabelCobrador))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabelUltimaCuota))
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonImprimirCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 61, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButtonGenerar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_SolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_SolicitudesMouseClicked
        int pos = tabla_Solicitudes.getSelectedRow();
        if (pos != -1 && listaCreditos.size()>1) {
            cargarDatosSoli(pos);
        }
        jButtonGenerar.setEnabled(true);
    }//GEN-LAST:event_tabla_SolicitudesMouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
       this.listaCreditos= creditosDao.getCreditosPendienteCobro();
       if(listaCreditos.size()<1){
           JOptionPane.showMessageDialog(null, "No hay creditos pendiente de generar carton", "Error", JOptionPane.ERROR_MESSAGE);
       }
       else{
           cargarTabla(listaCreditos);
       }
          
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        cartonGenerado=creditosDao.generarCarton(creditoSelected);
        if(cartonGenerado){
            jLabelInfo.setText("El carton se genero con exito");
            jButtonGenerar.setEnabled(false);
            jButtonImprimirCarton.setEnabled(true);
        }
        else{
            jLabelInfo.setText("no se pudo generar el carton");
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonImprimirCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirCartonActionPerformed
        if(!cartonGenerado){
            jLabelInfo.setText("No se puede imprimir el carton ya que no esta generado");
            return;
        }
        else{
            JasperViewer view =null;
            view = creditosDao.generarReporteCarton(creditoSelected.getId());
            if(view!= null){
                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                view.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonImprimirCartonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cartonGenerado=false;
        jLabelInfo.setText("");
         jLabelCreditoNumero.setText("");
        jLabelCantCuotas.setText("");
        jLabelCobrador.setText("");
        Date fecha = new Date();
        
        jLabelFechaInicioCobro.setText(Funciones.dateFormat2(fecha));
        
        jLabelImporteCredito.setText("");
        jLabelPlanSeleccionado.setText("no funca");
        jLabelNumCreditoUnificado.setText("no funca");
       
        jLabelImportCuota.setText("");
        
        jLabelUltimaCuota.setText("");
        jButtonGenerar.setEnabled(false);
        jButtonImprimirCarton.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonImprimirCarton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantCuotas;
    private javax.swing.JLabel jLabelCobrador;
    private javax.swing.JLabel jLabelCreditoNumero;
    private javax.swing.JLabel jLabelFechaInicioCobro;
    private javax.swing.JLabel jLabelImportCuota;
    private javax.swing.JLabel jLabelImporteCredito;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNumCreditoUnificado;
    private javax.swing.JLabel jLabelPlanSeleccionado;
    private javax.swing.JLabel jLabelUltimaCuota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTextArea jTextAreaObservacionesCredito;
    private javax.swing.JLabel lbl_administrador;
    private javax.swing.JLabel lbl_cobrador;
    private javax.swing.JLabel lbl_fechaAprobacion;
    private javax.swing.JLabel lbl_gerente;
    private javax.swing.JLabel lbl_vendedor;
    private javax.swing.JTable tabla_Solicitudes;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosSoli(int pos) {
        creditoSelected=listaCreditos.get(pos);
        jLabelCreditoNumero.setText(String.valueOf(creditoSelected.getId()));
        jLabelCantCuotas.setText(String.valueOf(creditoSelected.getCant_cuotas()));
        jLabelCobrador.setText(creditoSelected.getCobrador().getNombre());
        Date fecha = new Date();
        Date fechaVenci= new Date();
        creditoSelected.setVenc_pri_cuota((Timestamp) fecha);
        
        int cantDias =0;
        switch (creditoSelected.getPlan().getDia()){
            case 1 : 
                cantDias= creditoSelected.getCant_cuotas()/6;
                cantDias+=creditoSelected.getCant_cuotas();
                creditoSelected.setVenc_credito((Timestamp)Funciones.sumarRestarDiasFecha(fechaVenci,cantDias,0,0));
            case 6 :
                cantDias= creditoSelected.getCant_cuotas()*7;
                creditoSelected.setVenc_credito((Timestamp)Funciones.sumarRestarDiasFecha(fechaVenci,cantDias,0,0));
            case 30 :
                cantDias =  creditoSelected.getCant_cuotas()*30;
                creditoSelected.setVenc_credito((Timestamp)Funciones.sumarRestarDiasFecha(fechaVenci,cantDias,0,0));
        }
       
       
        jLabelFechaInicioCobro.setText(Funciones.dateFormat2(fecha));
        
        jLabelImporteCredito.setText(String.valueOf(creditoSelected.getImporte_credito()));
        jLabelPlanSeleccionado.setText("no funca");
        jLabelNumCreditoUnificado.setText("no funca");
       
        jLabelImportCuota.setText(String.valueOf(creditoSelected.getImporte_cuota()));
        
        jLabelUltimaCuota.setText(Funciones.dateFormat2(creditoSelected.getVenc_credito()));
        
    }

    private void cargarTabla(List<Credito> listaCreditos) {
      DefaultTableModel model = (DefaultTableModel) tabla_Solicitudes.getModel();
        model.setNumRows(0);
        
        listaCreditos.forEach((t) -> {
           Object[] o = new Object[3];
           o[0] = t.getId();
           o[1] = t.getCliente().getNombre();
           o[2] = t.getCobrador().getNombre();
           model.addRow(o);
        });
    }
   private void limpiarCampos(){
       jLabelCantCuotas.setText("123");
       jLabelCobrador.setText("");
       jLabelCreditoNumero.setText("");
       jLabelFechaInicioCobro.setText("_/_/_");
       jLabelImportCuota.setText("");
       jLabelImporteCredito.setText("");
       jLabelNumCreditoUnificado.setText("");
       jLabelPlanSeleccionado.setText("");
       jLabelUltimaCuota.setText("_/_/_");
       jTextAreaObservacionesCredito.setText("");
       
       lbl_cobrador.setText("Nombre de la persona que aprobo");
        lbl_administrador.setText("Nombre de la persona que aprobo");
        lbl_gerente.setText("Nombre de la persona que aprobo");
        lbl_vendedor.setText("Nombre de la persona que aprobo");
        lbl_fechaAprobacion.setText("");
   }
   
}
