/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import DAO.ClientesDAO;
import DAO.ComercioDAO;
import DAO.CreditosDAO;
import Statics.Funciones;
import javax.swing.JOptionPane;
import DAO.DireccionesDAO;
import DAO.EmpleadosDAO;
import DAO.RubroDAO;
import Models.Carton;
import Models.Cliente;
import Models.Comercio;
import Models.Credito;
import Models.Empleado;
import Models.Producto;
import Models.Rubro;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hernan
 */
public class ABMSolicitudesView extends javax.swing.JPanel {
    
    private DireccionesDAO direccionesDAO;
    private EmpleadosDAO empleadosDAO;
    private ClientesDAO clienteDAO;
    private CreditosDAO creditoDAO;
    private ComercioDAO comercioDAO;
    private Cliente clienteSelected;
    private ArrayList<Empleado> listCobradores;
    private ArrayList<Empleado> listVendedores;
    private List<Rubro> listRubros;
    private ArrayList<String> listZona;
    private List <Cliente> listaCliente;
    private ArrayList <Comercio> listaComercios;
    private int posComercioSelected;
    /**
     * Creates new form ABMSolicitudesView
     */
    public ABMSolicitudesView() {
        initComponents();
        clienteDAO = ClientesDAO.getInstance();
        empleadosDAO = EmpleadosDAO.getInstance();
        creditoDAO = CreditosDAO.getInstance();
        comercioDAO = ComercioDAO.getInstance();
        direccionesDAO = direccionesDAO.getInstance();
        cargarCbox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogClienteCargarDireccion = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButtonAñadirBarrio2 = new javax.swing.JButton();
        jButton_añadirCiudad_jDialog = new javax.swing.JButton();
        jComboBox_Ciudad_jDialog = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_barrio_JDialog = new javax.swing.JComboBox<>();
        jButton_añadirCalles_jDialog = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_provincia_jDialog = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField_codPostal_jDialog = new javax.swing.JTextField();
        jButton_añadirProvincia_jDialog = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField_numeroDireccion_jDialog = new javax.swing.JTextField();
        jComboBox_direccion_jDialog = new javax.swing.JComboBox<>();
        jButton_añadirCalle_jDialog = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField_referencia_jDialog = new javax.swing.JTextField();
        jDialogAñadirElemento = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jTextF_IngresarNuevoElemento = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btn_añadirNuevoElemento = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialogVerSolicitante = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lbl_domicilioCliente = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        lbl_nombreConyugue = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        lbl_estadoCivilClient = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        lbl_limiteCredito = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        lbl_documentoConyugue = new javax.swing.JLabel();
        lbl_nombreCliente = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        lbl_saldoActual = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        lbl_fechaNacimientoConyugue = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        lbl_barrioCliente = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        lbl_localidadCliente = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        lbl_provinciaCliente = new javax.swing.JLabel();
        lbl_contactoCliente = new javax.swing.JLabel();
        lbl_fechaNacimientoClient = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_creditosCliente = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_cuotasCredCliente = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbox_rubro = new javax.swing.JComboBox<>();
        txt_nombreComercio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_referenciaComercio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btn_nuevoRubro = new javax.swing.JButton();
        btn_añadirDireccionComercio = new javax.swing.JButton();
        cbox_habilitarDireccionComercio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbox_tipoIva = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_cuitComercio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_inicioActividades = new com.toedter.calendar.JDateChooser();
        cbox_EsPropietario = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cbox_zonas = new javax.swing.JComboBox<>();
        btn_añadirZona = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        btn_crearSolicitud = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dniCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nombreConyugue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btn_cargarRelacion = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_cantidadCreditos = new javax.swing.JLabel();
        cbox_cobrador = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cbox_vendedor = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        btn_verSolicitante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        txt_buscarCliente = new javax.swing.JTextField();
        rbtn_clientesNombre = new javax.swing.JRadioButton();
        rbtn_clientesDni = new javax.swing.JRadioButton();

        jLabel24.setText("Provincia");

        jButtonAñadirBarrio2.setText("+");
        jButtonAñadirBarrio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirBarrio2ActionPerformed(evt);
            }
        });

        jButton_añadirCiudad_jDialog.setText("+");
        jButton_añadirCiudad_jDialog.setEnabled(false);
        jButton_añadirCiudad_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirCiudad_jDialogActionPerformed(evt);
            }
        });

        jComboBox_Ciudad_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "La Punta", "Merlo", "Villa Mercedes" }));
        jComboBox_Ciudad_jDialog.setEnabled(false);
        jComboBox_Ciudad_jDialog.setPreferredSize(new java.awt.Dimension(59, 20));

        jLabel14.setText("Ciudad");

        jLabel15.setText("Barrio");

        jComboBox_barrio_JDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "UOCRA" }));
        jComboBox_barrio_JDialog.setEnabled(false);
        jComboBox_barrio_JDialog.setPreferredSize(new java.awt.Dimension(59, 20));

        jButton_añadirCalles_jDialog.setText("+");
        jButton_añadirCalles_jDialog.setEnabled(false);
        jButton_añadirCalles_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirCalles_jDialogActionPerformed(evt);
            }
        });

        jLabel16.setText("Direccion");

        jComboBox_provincia_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "San Luis" }));

        jLabel25.setText("Codigo Postal");

        jTextField_codPostal_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codPostal_jDialogActionPerformed(evt);
            }
        });

        jButton_añadirProvincia_jDialog.setText("+");
        jButton_añadirProvincia_jDialog.setEnabled(false);
        jButton_añadirProvincia_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirProvincia_jDialogActionPerformed(evt);
            }
        });

        jLabel30.setText("Numero");

        jTextField_numeroDireccion_jDialog.setEnabled(false);
        jTextField_numeroDireccion_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroDireccion_jDialogActionPerformed(evt);
            }
        });
        jTextField_numeroDireccion_jDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numeroDireccion_jDialogKeyTyped(evt);
            }
        });

        jComboBox_direccion_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "San Martin" }));
        jComboBox_direccion_jDialog.setEnabled(false);
        jComboBox_direccion_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_direccion_jDialogActionPerformed(evt);
            }
        });

        jButton_añadirCalle_jDialog.setText("+");
        jButton_añadirCalle_jDialog.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_direccion_jDialog, 0, 238, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Ciudad_jDialog, 0, 238, Short.MAX_VALUE)
                            .addComponent(jComboBox_barrio_JDialog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_provincia_jDialog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_añadirProvincia_jDialog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAñadirBarrio2)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_añadirCalle_jDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(162, 162, 162)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_codPostal_jDialog)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_numeroDireccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_añadirCalles_jDialog)
                            .addComponent(jButton_añadirCiudad_jDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAñadirBarrio2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_provincia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(jTextField_codPostal_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_añadirProvincia_jDialog)
                        .addComponent(jLabel24)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox_Ciudad_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCiudad_jDialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox_barrio_JDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCalles_jDialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel30)
                    .addComponent(jTextField_numeroDireccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_direccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCalle_jDialog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_ok.setText("OK");
        jButton_ok.setEnabled(false);
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");

        jLabel26.setText("Referencia");

        javax.swing.GroupLayout jDialogClienteCargarDireccionLayout = new javax.swing.GroupLayout(jDialogClienteCargarDireccion.getContentPane());
        jDialogClienteCargarDireccion.getContentPane().setLayout(jDialogClienteCargarDireccionLayout);
        jDialogClienteCargarDireccionLayout.setHorizontalGroup(
            jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ok))
                    .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_referencia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jDialogClienteCargarDireccionLayout.setVerticalGroup(
            jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField_referencia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton_ok))
                .addGap(41, 41, 41))
        );

        jTextF_IngresarNuevoElemento.setText("Ingrese nuevo");
        jTextF_IngresarNuevoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_IngresarNuevoElementoActionPerformed(evt);
            }
        });

        jLabel38.setText("Nuevo:");

        btn_añadirNuevoElemento.setText("OK");
        btn_añadirNuevoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirNuevoElementoActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_añadirNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jTextF_IngresarNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextF_IngresarNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_añadirNuevoElemento)
                    .addComponent(jButton13))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jDialogAñadirElementoLayout = new javax.swing.GroupLayout(jDialogAñadirElemento.getContentPane());
        jDialogAñadirElemento.getContentPane().setLayout(jDialogAñadirElementoLayout);
        jDialogAñadirElementoLayout.setHorizontalGroup(
            jDialogAñadirElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogAñadirElementoLayout.setVerticalGroup(
            jDialogAñadirElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialogVerSolicitante.setBackground(new java.awt.Color(255, 255, 255));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Datos del cliente:");

        jLabel50.setText("Domicilio:");

        lbl_domicilioCliente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_domicilioCliente.setText("El cliente ");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Conyugue");

        lbl_nombreConyugue.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_nombreConyugue.setText("nombre ");

        jLabel54.setText("Estado civil");

        lbl_estadoCivilClient.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_estadoCivilClient.setText("Aguante el poliamor");

        jLabel56.setText("Límite de crédito");

        lbl_limiteCredito.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_limiteCredito.setText("Ilimitado");

        jLabel58.setText("N° documento:");

        jLabel59.setText("Nombre:");

        lbl_documentoConyugue.setText("nombre ");

        lbl_nombreCliente.setText("asdasd");

        jLabel62.setText("Saldo actual");

        lbl_saldoActual.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_saldoActual.setText("Ilimitado");

        jLabel64.setText("Fecha de nacimiento:");

        lbl_fechaNacimientoConyugue.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_fechaNacimientoConyugue.setText("nombre ");

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel66.setText("Saldo y limites");

        jLabel67.setText("Contacto:");

        jLabel69.setText("Fecha de nacimiento:");

        jLabel70.setText("Barrio:");

        lbl_barrioCliente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_barrioCliente.setText("El cliente ");

        jLabel72.setText("Localidad:");

        lbl_localidadCliente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_localidadCliente.setText("El cliente ");

        jLabel74.setText("Provincia:");

        lbl_provinciaCliente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_provinciaCliente.setText("El cliente ");

        lbl_contactoCliente.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_contactoCliente.setText("El cliente ");

        lbl_fechaNacimientoClient.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lbl_fechaNacimientoClient.setText("Aguante el poliamor");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70)
                            .addComponent(jLabel50)
                            .addComponent(jLabel54))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_barrioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_domicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel66)
                                        .addGap(20, 20, 20))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel62)
                                        .addGap(38, 38, 38))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_saldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_limiteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lbl_estadoCivilClient)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel69)
                            .addComponent(jLabel67))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_contactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_fechaNacimientoClient))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)
                            .addComponent(jLabel64)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel72)
                                    .addGap(17, 17, 17)
                                    .addComponent(lbl_localidadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel74)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_provinciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(61, 61, 61)))))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_fechaNacimientoConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_documentoConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombreConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel66)
                    .addComponent(jLabel47)
                    .addComponent(lbl_nombreCliente))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl_saldoActual)
                    .addComponent(lbl_localidadCliente)
                    .addComponent(jLabel72)
                    .addComponent(lbl_domicilioCliente)
                    .addComponent(jLabel50)
                    .addComponent(jLabel62))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel70)
                    .addComponent(lbl_barrioCliente)
                    .addComponent(jLabel74)
                    .addComponent(lbl_provinciaCliente)
                    .addComponent(lbl_limiteCredito)
                    .addComponent(jLabel56))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(lbl_estadoCivilClient)
                            .addComponent(jLabel52))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(lbl_contactoCliente))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(lbl_fechaNacimientoClient)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel59)
                            .addComponent(lbl_nombreConyugue))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_documentoConyugue, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(lbl_fechaNacimientoConyugue))))
                .addGap(22, 22, 22))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Datos crediticios");

        tabla_creditosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Crédito", "Cant cuotas", "Deuda", "Importe crédito", "Estado", "Tipo", "Cobrador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_creditosCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_creditosClienteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_creditosCliente);

        tabla_cuotasCredCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "# Cuota", "Importe cuota", "Importe cancelado", "Estado", "Vencimiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tabla_cuotasCredCliente);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel48.setText("Creditos y solicitudes");

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel49.setText("Cuotas");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel49)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogVerSolicitanteLayout = new javax.swing.GroupLayout(jDialogVerSolicitante.getContentPane());
        jDialogVerSolicitante.getContentPane().setLayout(jDialogVerSolicitanteLayout);
        jDialogVerSolicitanteLayout.setHorizontalGroup(
            jDialogVerSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerSolicitanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogVerSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogVerSolicitanteLayout.setVerticalGroup(
            jDialogVerSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogVerSolicitanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setText("DATOS DEL COMERCIO");

        jLabel17.setText("Nombre");

        jLabel18.setText("Rubro");

        cbox_rubro.setPreferredSize(new java.awt.Dimension(59, 20));
        cbox_rubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_rubroActionPerformed(evt);
            }
        });

        txt_nombreComercio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreComercioKeyReleased(evt);
            }
        });

        jLabel19.setText("El comercio se ubica en el domicilio del cliente:");

        txt_referenciaComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_referenciaComercioActionPerformed(evt);
            }
        });

        jLabel23.setText("Referencia");

        btn_nuevoRubro.setText("+");
        btn_nuevoRubro.setEnabled(false);
        btn_nuevoRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoRubroActionPerformed(evt);
            }
        });

        btn_añadirDireccionComercio.setText("Cargar Direccion");
        btn_añadirDireccionComercio.setEnabled(false);
        btn_añadirDireccionComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirDireccionComercioActionPerformed(evt);
            }
        });

        cbox_habilitarDireccionComercio.setText("NO");
        cbox_habilitarDireccionComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_habilitarDireccionComercioActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Iva");

        cbox_tipoIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consumidor Final", "Excento de iva", "Monotributo", "No responsable de iva", "Responsable inscripto" }));

        jLabel2.setText("N° CUIT");

        jLabel3.setText("Inicio de Actividades");

        cbox_EsPropietario.setText("Si");

        jLabel31.setText("Es propetario?");

        jLabel28.setText("Zona");

        cbox_zonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "zona 1", "zona 2" }));
        cbox_zonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_zonasActionPerformed(evt);
            }
        });

        btn_añadirZona.setText("+");
        btn_añadirZona.setEnabled(false);
        btn_añadirZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirZonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreComercio)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbox_rubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_nuevoRubro))))
                    .addComponent(txt_referenciaComercio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel6))
                            .addComponent(jLabel23))
                        .addGap(26, 26, 26)
                        .addComponent(cbox_habilitarDireccionComercio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btn_añadirDireccionComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbox_tipoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(date_inicioActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txt_cuitComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(29, 29, 29)
                                .addComponent(cbox_EsPropietario)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel28)
                                .addGap(26, 26, 26)
                                .addComponent(cbox_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_añadirZona)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_nombreComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbox_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nuevoRubro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_añadirDireccionComercio)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(cbox_habilitarDireccionComercio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(cbox_EsPropietario)
                    .addComponent(jLabel28)
                    .addComponent(cbox_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_añadirZona, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(txt_referenciaComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbox_tipoIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cuitComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_inicioActividades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Buscar Cliente");

        btn_crearSolicitud.setBackground(new java.awt.Color(255, 255, 255));
        btn_crearSolicitud.setText("Nueva solicitud");
        btn_crearSolicitud.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_crearSolicitud.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_crearSolicitud.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_crearSolicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crearSolicitudMouseClicked(evt);
            }
        });
        btn_crearSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearSolicitudActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        txt_nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("DNI");

        txt_dniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dniClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Conyugue");

        jLabel4.setText("Solicitud Numero:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btn_cargarRelacion.setBackground(new java.awt.Color(255, 255, 255));
        btn_cargarRelacion.setText("Cargar Relacion");
        btn_cargarRelacion.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_cargarRelacion.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_cargarRelacion.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_cargarRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargarRelacionMouseClicked(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_cancelar.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_cancelar.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });

        jLabel9.setText("Total de creditos solicitados por el Titular y el Conyuge:");

        lbl_cantidadCreditos.setText("label???");

        cbox_cobrador.setEnabled(false);

        jLabel34.setText("Cobrador:");

        jLabel35.setText("Asignar Cobrador");

        cbox_vendedor.setEnabled(false);

        jLabel36.setText("Vendedor:");

        btn_verSolicitante.setText("Historial crediticio");
        btn_verSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verSolicitanteActionPerformed(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        txt_buscarCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_buscarClienteCaretUpdate(evt);
            }
        });
        txt_buscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarClienteMouseClicked(evt);
            }
        });
        txt_buscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscarClienteKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbtn_clientesNombre);
        rbtn_clientesNombre.setText("Nombre");

        buttonGroup1.add(rbtn_clientesDni);
        rbtn_clientesDni.setSelected(true);
        rbtn_clientesDni.setText("DNI");
        rbtn_clientesDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_clientesDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_clientesDni)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_clientesNombre)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(46, 46, 46)
                                .addComponent(txt_nombreCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(69, 69, 69)
                                .addComponent(txt_dniCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(38, 38, 38)
                                .addComponent(txt_nombreConyugue))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(lbl_cantidadCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbox_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbox_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cargarRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_verSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel41))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_crearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtn_clientesDni)
                            .addComponent(rbtn_clientesNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_nombreConyugue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lbl_cantidadCreditos))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel36)
                                    .addComponent(cbox_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(cbox_cobrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarRelacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_crearSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_verSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_rubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_rubroActionPerformed
        // TODO add your handling code here:
        btn_nuevoRubro.setEnabled(true);
    }//GEN-LAST:event_cbox_rubroActionPerformed

    private void txt_referenciaComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_referenciaComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_referenciaComercioActionPerformed

    private void btn_nuevoRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoRubroActionPerformed
        // TODO add your handling code here:
        jDialogAñadirElemento.setVisible(true);
        jDialogAñadirElemento.setModal(true);
        jDialogAñadirElemento.setLocationRelativeTo(this);
        jDialogAñadirElemento.setSize(400,221);
        jDialogAñadirElemento.setTitle("Añadir un nuevo Rubro");
    }//GEN-LAST:event_btn_nuevoRubroActionPerformed

    private void btn_añadirDireccionComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirDireccionComercioActionPerformed
        // TODO add your handling code here:
        jDialogClienteCargarDireccion.setVisible(true);
        jDialogClienteCargarDireccion.setModal(true);
        jDialogClienteCargarDireccion.setLocationRelativeTo(this);
        //jDialogClienteCargarDireccion.setSize(400,221);
        jDialogClienteCargarDireccion.setTitle("Añadir la direccion del comercio");
    }//GEN-LAST:event_btn_añadirDireccionComercioActionPerformed

    private void cbox_habilitarDireccionComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_habilitarDireccionComercioActionPerformed
        btn_añadirDireccionComercio.setEnabled(true);
    }//GEN-LAST:event_cbox_habilitarDireccionComercioActionPerformed

    private void btn_crearSolicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crearSolicitudMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearSolicitudMouseClicked

    private void btn_crearSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearSolicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crearSolicitudActionPerformed

    private void btn_cargarRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargarRelacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cargarRelacionMouseClicked

    private void txt_nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreClienteActionPerformed

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void cbox_zonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_zonasActionPerformed
        // TODO add your handling code here:
        btn_añadirZona.setEnabled(true);

    }//GEN-LAST:event_cbox_zonasActionPerformed

    private void btn_añadirZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirZonaActionPerformed
        // TODO add your handling code here:
        jDialogAñadirElemento.setVisible(true);
        jDialogAñadirElemento.setModal(true);
        jDialogAñadirElemento.setLocationRelativeTo(this);
        jDialogAñadirElemento.setSize(400,221);
        jDialogAñadirElemento.setTitle("Añadir una nueva Zona");
    }//GEN-LAST:event_btn_añadirZonaActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txt_dniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dniClienteActionPerformed

    private void jButtonAñadirBarrio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirBarrio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirBarrio2ActionPerformed

    private void jButton_añadirCiudad_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirCiudad_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirCiudad_jDialogActionPerformed

    private void jButton_añadirCalles_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirCalles_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirCalles_jDialogActionPerformed

    private void jTextField_codPostal_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codPostal_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codPostal_jDialogActionPerformed

    private void jButton_añadirProvincia_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirProvincia_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirProvincia_jDialogActionPerformed

    private void jTextField_numeroDireccion_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroDireccion_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroDireccion_jDialogActionPerformed

    private void jTextField_numeroDireccion_jDialogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numeroDireccion_jDialogKeyTyped
        // TODO add your handling code here:
        jButton_ok.setEnabled(true);
    }//GEN-LAST:event_jTextField_numeroDireccion_jDialogKeyTyped

    private void jComboBox_direccion_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_direccion_jDialogActionPerformed
        // TODO add your handling code here:
        jTextField_numeroDireccion_jDialog.setEnabled(true);
    }//GEN-LAST:event_jComboBox_direccion_jDialogActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // TODO add your handling code here:
        //At the end of all controls, it enables the flag of the commerce address;

        if(Funciones.compareStrings("-",String.valueOf(jComboBox_provincia_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null,"Debe ingresar una provincia valida","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Funciones.compareStrings("-", String.valueOf(jComboBox_Ciudad_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null,"Debe ingresar una ciudad validad","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Funciones.compareStrings("-",String.valueOf(jComboBox_direccion_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null, "Debe ingresar una direccion valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!Funciones.isNumeric(jTextField_numeroDireccion_jDialog.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar un numero de direccion","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!Funciones.isNumeric(jTextField_codPostal_jDialog.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar un codigo postal","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_jButton_okActionPerformed

    private void jTextF_IngresarNuevoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_IngresarNuevoElementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF_IngresarNuevoElementoActionPerformed

    private void btn_añadirNuevoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirNuevoElementoActionPerformed
        String textoInput= jTextF_IngresarNuevoElemento.getText().toLowerCase();
        switch(jDialogAñadirElemento.getTitle()){
            case "Añadir una nueva Nacionalidad":{
                direccionesDAO.añadirNacionalidad(textoInput);
                jCombo_Naciones.addItem(textoInput);
                jCombo_Naciones.setSelectedItem(textoInput);
                break;
            }
            case "Añadir una nueva Provincia":{
                direccionesDAO.añadirProvincia(textoInput);
                jComboBox_Provincias.addItem(textoInput);
                jComboBox_Provincias.setSelectedItem(textoInput);
            }
            case "Añadir una nueva Ciudad":{
                direccionesDAO.añadirCiudad(textoInput);
                jComboBox_Ciudades.addItem(textoInput);
                jComboBox_Ciudades.setSelectedItem(textoInput);
                break;
            }
            case "Añadir un nuevo Barrio":{
                direccionesDAO.añadirBarrio(textoInput);
                jComboBox_Barrios.addItem(textoInput);
                jComboBox_Barrios.setSelectedItem(textoInput);
                break;
            }
            case "Añadir una nueva Calle/Manzana":{
                direccionesDAO.añadirDireccion(textoInput);
                jComboBox_calles.addItem(textoInput);
                jComboBox_calles.setSelectedItem(textoInput);
                break;
            }
            case "Añadir un nuevo tipo de contacto":{
                //quizas necesite un contactosDAO
            }
            case "Añadir una nueva Zona":{
                //quizas necesite un zonaDAO
            }
        }
    }//GEN-LAST:event_btn_añadirNuevoElementoActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void btn_verSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verSolicitanteActionPerformed
        jDialogVerSolicitante.setTitle("Datos del solicitante");
        jDialogVerSolicitante.setVisible(true);
        jDialogVerSolicitante.setModal(true);
        jDialogVerSolicitante.setSize(875, 714);
        jDialogVerSolicitante.setLocationRelativeTo(this);
        cargarDatosSolicitante();
    }//GEN-LAST:event_btn_verSolicitanteActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        int pos= jTableClientes.getSelectedRow();
        if(pos!=-1){
            cargarDatosCliente(pos);
            habilitarBotones(true);
        }
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void txt_buscarClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_buscarClienteCaretUpdate
        cambioBusqueda(txt_buscarCliente.getText().toString(),rbtn_clientesDni.isSelected(),rbtn_clientesNombre.isSelected(),txt_buscarCliente,jTableClientes);
    }//GEN-LAST:event_txt_buscarClienteCaretUpdate

    private void txt_buscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarClienteMouseClicked

    private void txt_buscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarClienteKeyTyped

        char c = evt.getKeyChar();
        if (this.rbtn_clientesDni.isSelected()) {
            if ((c < '0' || c > '9')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txt_buscarClienteKeyTyped

    private void rbtn_clientesDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_clientesDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_clientesDniActionPerformed

    private void tabla_creditosClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_creditosClienteMouseClicked
        if(tabla_creditosCliente.getSelectedRow() != -1){
            int idCredito = (int) tabla_creditosCliente.getValueAt(tabla_creditosCliente.getSelectedRow(), 0);
            cargarCuotasCredito(idCredito);
        }
    }//GEN-LAST:event_tabla_creditosClienteMouseClicked

    private void txt_nombreComercioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreComercioKeyReleased
        if(listaComercios!=null && listaComercios.size() > 0){
            if(evt.getExtendedKeyCode() == java.awt.event.KeyEvent.VK_DOWN){
                posComercioSelected = (posComercioSelected+1)%listaComercios.size();
                txt_nombreComercio.setText(listaComercios.get(posComercioSelected).getNombre());
                cbox_rubro.setSelectedItem(listaComercios.get(posComercioSelected).getRubro());
                txt_referenciaComercio.setText(listaComercios.get(posComercioSelected).getReferencia());
                txt_cuitComercio.setText(listaComercios.get(posComercioSelected).getCuit());
                date_inicioActividades.setDate(listaComercios.get(posComercioSelected).getIncio_actividades());
                cbox_tipoIva.setSelectedItem(listaComercios.get(posComercioSelected).getTipo_iva());
                cbox_zonas.setSelectedItem(listaComercios.get(posComercioSelected).getZona());
                cbox_EsPropietario.setSelected(listaComercios.get(posComercioSelected).getPropietario() ==1);
                boolean val = listaComercios.get(posComercioSelected).getDireccion().getId() != clienteSelected.getDireccion_id();
                cbox_habilitarDireccionComercio.setSelected(val);
                btn_añadirDireccionComercio.setEnabled(val);
            }else if(evt.getExtendedKeyCode() == java.awt.event.KeyEvent.VK_UP){
                if(posComercioSelected == 0){
                    posComercioSelected = listaComercios.size()-1;
                }else{
                    posComercioSelected--;
                }
                txt_nombreComercio.setText(listaComercios.get(posComercioSelected).getNombre());
            }
        }
    }//GEN-LAST:event_txt_nombreComercioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirDireccionComercio;
    private javax.swing.JButton btn_añadirNuevoElemento;
    private javax.swing.JButton btn_añadirZona;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cargarRelacion;
    private javax.swing.JButton btn_crearSolicitud;
    private javax.swing.JButton btn_nuevoRubro;
    private javax.swing.JButton btn_verSolicitante;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbox_EsPropietario;
    private javax.swing.JComboBox<Models.Empleado> cbox_cobrador;
    private javax.swing.JCheckBox cbox_habilitarDireccionComercio;
    private javax.swing.JComboBox<Models.Rubro> cbox_rubro;
    private javax.swing.JComboBox<String> cbox_tipoIva;
    private javax.swing.JComboBox<Models.Empleado> cbox_vendedor;
    private javax.swing.JComboBox<String> cbox_zonas;
    private com.toedter.calendar.JDateChooser date_inicioActividades;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAñadirBarrio2;
    private javax.swing.JButton jButton_añadirCalle_jDialog;
    private javax.swing.JButton jButton_añadirCalles_jDialog;
    private javax.swing.JButton jButton_añadirCiudad_jDialog;
    private javax.swing.JButton jButton_añadirProvincia_jDialog;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JComboBox<String> jComboBox_Ciudad_jDialog;
    private javax.swing.JComboBox<String> jComboBox_barrio_JDialog;
    private javax.swing.JComboBox<String> jComboBox_direccion_jDialog;
    private javax.swing.JComboBox<String> jComboBox_provincia_jDialog;
    private javax.swing.JDialog jDialogAñadirElemento;
    private javax.swing.JDialog jDialogClienteCargarDireccion;
    private javax.swing.JDialog jDialogVerSolicitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextF_IngresarNuevoElemento;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField_codPostal_jDialog;
    private javax.swing.JTextField jTextField_numeroDireccion_jDialog;
    private javax.swing.JTextField jTextField_referencia_jDialog;
    private javax.swing.JLabel lbl_barrioCliente;
    private javax.swing.JLabel lbl_cantidadCreditos;
    private javax.swing.JLabel lbl_contactoCliente;
    private javax.swing.JLabel lbl_documentoConyugue;
    private javax.swing.JLabel lbl_domicilioCliente;
    private javax.swing.JLabel lbl_estadoCivilClient;
    private javax.swing.JLabel lbl_fechaNacimientoClient;
    private javax.swing.JLabel lbl_fechaNacimientoConyugue;
    private javax.swing.JLabel lbl_limiteCredito;
    private javax.swing.JLabel lbl_localidadCliente;
    private javax.swing.JLabel lbl_nombreCliente;
    private javax.swing.JLabel lbl_nombreConyugue;
    private javax.swing.JLabel lbl_provinciaCliente;
    private javax.swing.JLabel lbl_saldoActual;
    protected javax.swing.JRadioButton rbtn_clientesDni;
    protected javax.swing.JRadioButton rbtn_clientesNombre;
    private javax.swing.JTable tabla_creditosCliente;
    private javax.swing.JTable tabla_cuotasCredCliente;
    protected javax.swing.JTextField txt_buscarCliente;
    private javax.swing.JTextField txt_cuitComercio;
    private javax.swing.JTextField txt_dniCliente;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_nombreComercio;
    private javax.swing.JTextField txt_nombreConyugue;
    private javax.swing.JTextField txt_referenciaComercio;
    // End of variables declaration//GEN-END:variables
//panel buscador
    public void cambioBusqueda(String txt,boolean dni,boolean nombre,JTextField buscador, JTable tablaBuscador ){
        if(txt.isEmpty()){
            System.out.println("Entre por txt empty");
            cargarTablaBusqueda(clienteDAO.buscarCliente("nombre",""),tablaBuscador);
            
        }else if(dni){
            try{
                int cod= Integer.parseInt(txt);
                cargarTablaBusqueda(clienteDAO.buscarCliente("id",cod+""),tablaBuscador);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Debe ingresar un dni",
                            "Error", JOptionPane.ERROR_MESSAGE);
                 txt_buscarCliente.setText("");
                 buscador.setText("");
            }
        }else if(nombre){
            cargarTablaBusqueda(clienteDAO.buscarCliente("nombre",txt.toLowerCase()),tablaBuscador);
            
        }else {
             System.out.println("Error no selecciono tipo de busqueda");
        }
    }
    public void cargarTablaBusqueda(List<Cliente> client, JTable tablaBuscador){
        listaCliente=client;
        DefaultTableModel model = (DefaultTableModel) tablaBuscador.getModel();
        model.setNumRows(0);
        try{
            Object[] obj = new Object [2];
            for (int i=0; i< listaCliente.size();i++){
            obj[0]=listaCliente.get(i).getDni();
            obj[1]=listaCliente.get(i).getNombre();
            model.addRow(obj);
        }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

    private void cargarCbox() {
        
        cbox_cobrador.setEnabled(true);
        listCobradores = empleadosDAO.getCobradores();
        Collections.sort(listCobradores);
        listCobradores.forEach((t) -> {
            cbox_cobrador.addItem(t);
        });
        cbox_cobrador.setEnabled(false);
        
        cbox_vendedor.setEnabled(true);
        listVendedores = empleadosDAO.getVendedores();
        Collections.sort(listVendedores);
        listVendedores.forEach((t) -> {
            cbox_vendedor.addItem(t);
        });
        cbox_vendedor.setEnabled(false);
        
        cbox_rubro.setEnabled(true);
        listRubros = RubroDAO.getInstance().getRubros();
        Collections.sort(listVendedores);
        listRubros.forEach((t) -> {
            cbox_rubro.addItem(t);
        });
        cbox_rubro.setEnabled(false);
        cbox_zonas.setEnabled(true);
        listZona = comercioDAO.getZona();
        Collections.sort(listVendedores);
        listZona.forEach((t) -> {
            cbox_zonas.addItem(t);
        });
        cbox_zonas.setEnabled(false);
    }
    //METODOS jDialog VER SOLICITANTE
    private void cargarDatosSolicitante() {
        ArrayList<Credito> cred = creditoDAO.getCreditosCliente(clienteSelected.getId());
        DefaultTableModel model = (DefaultTableModel) tabla_creditosCliente.getModel();
        float saldoActual = 0f;
        for(int i = 0 ; i < cred.size(); i++){
            Object[] o = new Object[6];
            o[0] = cred.get(i).getId();
            o[1] = cred.get(i).getCant_cuotas();
            o[2] = cred.get(i).getImporte_deuda();
            o[3] = cred.get(i).getImporte_credito();
            o[4] = cred.get(i).getEstado();
            o[5] = cred.get(i).getTipo();
            if(cred.get(i).getCobrador() != null)
                o[6] = cred.get(i).getCobrador().getNombre();
            else
                o[6] = "-";
            saldoActual += cred.get(i).getImporte_deuda();
            model.addRow(o);
        }
        Cliente conyugue = clienteDAO.recuperarConyugue(clienteSelected.getId());
        Cliente cliente = clienteDAO.buscarCliente(clienteSelected.getId());
        lbl_fechaNacimientoClient.setText(Statics.Funciones.dateFormat(cliente.getFechaNacimiento()));
        if(cliente.getContacto().size()>0)
            lbl_contactoCliente.setText(cliente.getContacto().get(0).getContacto());
        lbl_nombreCliente.setText(cliente.getNombre());
        lbl_domicilioCliente.setText(cliente.getDireccion()+" "+cliente.getNumero());
        lbl_estadoCivilClient.setText(cliente.getEstadoCivil());
        lbl_localidadCliente.setText(cliente.getCiudad());
        lbl_barrioCliente.setText(cliente.getBarrio());
        lbl_provinciaCliente.setText(cliente.getProvincia());
        //datos monetarios we
        lbl_limiteCredito.setText(cliente.getLimite_credito()+"");
        lbl_saldoActual.setText(saldoActual+"");
        //datos conyugue
        lbl_nombreConyugue.setText(conyugue.getNombre());
        lbl_fechaNacimientoConyugue.setText(Statics.Funciones.dateFormat(conyugue.getFechaNacimiento()));
        lbl_documentoConyugue.setText(conyugue.getDni()+"");
        
    }
    private void cargarCuotasCredito(int idCredito) {
        ArrayList<Carton> cartones = creditoDAO.getCartonesCredito(idCredito);
        DefaultTableModel model = (DefaultTableModel) tabla_creditosCliente.getModel();
        for (int i = 0; i < cartones.size(); i++) {
            Object[] o = new Object[5];
            o[0] = cartones.get(i).getNro_cuota();
            o[1] = cartones.get(i).getImporte_cuota();
            o[2] = cartones.get(i).getImporte_cancelado();
            o[3] = cartones.get(i).getEstado();
            o[4] = Statics.Funciones.dateParse(cartones.get(i).getVencimiento());
            model.addRow(o);
        }
    }
    
    //FIN METODOS jDialog VER SOLICITANTE
    private void cargarDatosCliente(int pos) {
        if(pos !=-1){
            clienteSelected = listaCliente.get(pos);
            txt_nombreCliente.setText(clienteSelected.getNombre());
            txt_dniCliente.setText(clienteSelected.getDni()+"");
            //Dato conyugue
            Cliente c = clienteDAO.recuperarConyugue(clienteSelected.getId());
            txt_nombreConyugue.setText(c.getNombre()+ " ("+c.getDni()+")");
            //cantidad creditos
            int cant = creditoDAO.getCantCredPorPareja(clienteSelected.getId(),c.getId());
            lbl_cantidadCreditos.setText(cant+"");
            //datos comercios
            listaComercios = comercioDAO.getComerciosByCliente(clienteSelected.getId());
            Comercio com = new Comercio();
            com.setId(-1);
            listaComercios.add(com);
            
        }
            
    }

    private void habilitarBotones(boolean b) {
        btn_añadirDireccionComercio.setEnabled(b);
            btn_cancelar.setEnabled(b);
            btn_crearSolicitud.setEnabled(b);
            btn_verSolicitante.setEnabled(b);
            btn_cargarRelacion.setEnabled(b);
            btn_nuevoRubro.setEnabled(b);
    }
}
