/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Statics.Funciones;
import javax.swing.JOptionPane;
import DAO.DireccionesDAO;
import Models.Cliente;
import Models.Solicitud;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hernan
 */
public class ABMSolicitudesView extends javax.swing.JPanel {
    
    private DireccionesDAO direccionesDAO;
    /**
     * Creates new form ABMSolicitudesView
     */
    public ABMSolicitudesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogClienteCargarDireccion = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jButtonAñadirBarrio2 = new javax.swing.JButton();
        jButton_añadirCiudad_jDialog = new javax.swing.JButton();
        jComboBox_Ciudad_jDialog = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_barrio_JDialog = new javax.swing.JComboBox<>();
        jButton_añadirCalles_jDialog = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_provincia_jDialog = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField_codPostal_jDialog = new javax.swing.JTextField();
        jButton_añadirProvincia_jDialog = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField_numeroDireccion_jDialog = new javax.swing.JTextField();
        jComboBox_direccion_jDialog = new javax.swing.JComboBox<>();
        jButton_añadirCalle_jDialog = new javax.swing.JButton();
        jButton_ok = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField_referencia_jDialog = new javax.swing.JTextField();
        jDialogAñadirElemento = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jTextF_IngresarNuevoElemento = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        btn_añadirNuevoElemento = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox_rubro = new javax.swing.JComboBox<>();
        jTextField_nombreComercio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_referenciaComercio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton_añadirRubro = new javax.swing.JButton();
        btn_añadirDireccionComercio = new javax.swing.JButton();
        jCheckBox_habilitarDireccionComercio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCheckBox_EsPropietario = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox_zonas = new javax.swing.JComboBox<>();
        jButton_añadirZona = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jTextField_buscarCliente = new javax.swing.JTextField();
        rbtn_clientesDni = new javax.swing.JRadioButton();
        rbtn_clientesNombre = new javax.swing.JRadioButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabla_clientes_busqueda = new javax.swing.JTable();
        btn_proveedores_eliminar = new javax.swing.JButton();
        btn_proveedores_modificar = new javax.swing.JButton();
        btn_proveedores_nuevo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btn_proveedores_nuevo1 = new javax.swing.JButton();
        btn_proveedores_nuevo2 = new javax.swing.JButton();
        btn_proveedores_nuevo3 = new javax.swing.JButton();
        btn_proveedores_nuevo4 = new javax.swing.JButton();
        btn_proveedores_nuevo5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel24.setText("Provincia");

        jButtonAñadirBarrio2.setText("+");
        jButtonAñadirBarrio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirBarrio2ActionPerformed(evt);
            }
        });

        jButton_añadirCiudad_jDialog.setText("+");
        jButton_añadirCiudad_jDialog.setEnabled(false);
        jButton_añadirCiudad_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirCiudad_jDialogActionPerformed(evt);
            }
        });

        jComboBox_Ciudad_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "La Punta", "Merlo", "Villa Mercedes" }));
        jComboBox_Ciudad_jDialog.setEnabled(false);
        jComboBox_Ciudad_jDialog.setPreferredSize(new java.awt.Dimension(59, 20));

        jLabel14.setText("Ciudad");

        jLabel15.setText("Barrio");

        jComboBox_barrio_JDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "UOCRA" }));
        jComboBox_barrio_JDialog.setEnabled(false);
        jComboBox_barrio_JDialog.setPreferredSize(new java.awt.Dimension(59, 20));

        jButton_añadirCalles_jDialog.setText("+");
        jButton_añadirCalles_jDialog.setEnabled(false);
        jButton_añadirCalles_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirCalles_jDialogActionPerformed(evt);
            }
        });

        jLabel16.setText("Direccion");

        jComboBox_provincia_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "San Luis" }));

        jLabel25.setText("Codigo Postal");

        jTextField_codPostal_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codPostal_jDialogActionPerformed(evt);
            }
        });

        jButton_añadirProvincia_jDialog.setText("+");
        jButton_añadirProvincia_jDialog.setEnabled(false);
        jButton_añadirProvincia_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirProvincia_jDialogActionPerformed(evt);
            }
        });

        jLabel30.setText("Numero");

        jTextField_numeroDireccion_jDialog.setEnabled(false);
        jTextField_numeroDireccion_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_numeroDireccion_jDialogActionPerformed(evt);
            }
        });
        jTextField_numeroDireccion_jDialog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_numeroDireccion_jDialogKeyTyped(evt);
            }
        });

        jComboBox_direccion_jDialog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "San Martin" }));
        jComboBox_direccion_jDialog.setEnabled(false);
        jComboBox_direccion_jDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_direccion_jDialogActionPerformed(evt);
            }
        });

        jButton_añadirCalle_jDialog.setText("+");
        jButton_añadirCalle_jDialog.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_direccion_jDialog, 0, 238, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Ciudad_jDialog, 0, 238, Short.MAX_VALUE)
                            .addComponent(jComboBox_barrio_JDialog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_provincia_jDialog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_añadirProvincia_jDialog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAñadirBarrio2)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton_añadirCalle_jDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(162, 162, 162)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_codPostal_jDialog)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_numeroDireccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_añadirCalles_jDialog)
                            .addComponent(jButton_añadirCiudad_jDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAñadirBarrio2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_provincia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addComponent(jTextField_codPostal_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_añadirProvincia_jDialog)
                        .addComponent(jLabel24)))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox_Ciudad_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCiudad_jDialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox_barrio_JDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCalles_jDialog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel30)
                    .addComponent(jTextField_numeroDireccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_direccion_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirCalle_jDialog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_ok.setText("OK");
        jButton_ok.setEnabled(false);
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");

        jLabel26.setText("Referencia");

        javax.swing.GroupLayout jDialogClienteCargarDireccionLayout = new javax.swing.GroupLayout(jDialogClienteCargarDireccion.getContentPane());
        jDialogClienteCargarDireccion.getContentPane().setLayout(jDialogClienteCargarDireccionLayout);
        jDialogClienteCargarDireccionLayout.setHorizontalGroup(
            jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_ok))
                    .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_referencia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jDialogClienteCargarDireccionLayout.setVerticalGroup(
            jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogClienteCargarDireccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField_referencia_jDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jDialogClienteCargarDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton_ok))
                .addGap(41, 41, 41))
        );

        jTextF_IngresarNuevoElemento.setText("Ingrese nuevo");
        jTextF_IngresarNuevoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextF_IngresarNuevoElementoActionPerformed(evt);
            }
        });

        jLabel38.setText("Nuevo:");

        btn_añadirNuevoElemento.setText("OK");
        btn_añadirNuevoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirNuevoElementoActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_añadirNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jTextF_IngresarNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextF_IngresarNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_añadirNuevoElemento)
                    .addComponent(jButton13))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout jDialogAñadirElementoLayout = new javax.swing.GroupLayout(jDialogAñadirElemento.getContentPane());
        jDialogAñadirElemento.getContentPane().setLayout(jDialogAñadirElementoLayout);
        jDialogAñadirElementoLayout.setHorizontalGroup(
            jDialogAñadirElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogAñadirElementoLayout.setVerticalGroup(
            jDialogAñadirElementoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel6.setText("DATOS DEL COMERCIO");

        jLabel17.setText("Nombre");

        jLabel18.setText("Rubro");

        jComboBox_rubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "rubro 1", "rubro 2" }));
        jComboBox_rubro.setPreferredSize(new java.awt.Dimension(59, 20));
        jComboBox_rubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_rubroActionPerformed(evt);
            }
        });

        jTextField_nombreComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreComercioActionPerformed(evt);
            }
        });

        jLabel19.setText("El comercio se ubica en el domicilio del cliente:");

        jTextField_referenciaComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_referenciaComercioActionPerformed(evt);
            }
        });

        jLabel23.setText("Referencia");

        jButton_añadirRubro.setText("+");
        jButton_añadirRubro.setEnabled(false);
        jButton_añadirRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirRubroActionPerformed(evt);
            }
        });

        btn_añadirDireccionComercio.setText("Cargar Direccion");
        btn_añadirDireccionComercio.setEnabled(false);
        btn_añadirDireccionComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirDireccionComercioActionPerformed(evt);
            }
        });

        jCheckBox_habilitarDireccionComercio.setText("NO");
        jCheckBox_habilitarDireccionComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_habilitarDireccionComercioActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Iva");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("N° CUIT");

        jTextField1.setText("jTextField1");

        jLabel3.setText("Inicio de Actividades");

        jCheckBox_EsPropietario.setText("Si");

        jLabel31.setText("Es propetario?");

        jLabel28.setText("Zona");

        jComboBox_zonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "zona 1", "zona 2" }));
        jComboBox_zonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_zonasActionPerformed(evt);
            }
        });

        jButton_añadirZona.setText("+");
        jButton_añadirZona.setEnabled(false);
        jButton_añadirZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadirZonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombreComercio)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox_rubro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_añadirRubro))))
                    .addComponent(jTextField_referenciaComercio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel6))
                            .addComponent(jLabel23))
                        .addGap(26, 26, 26)
                        .addComponent(jCheckBox_habilitarDireccionComercio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btn_añadirDireccionComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(33, 33, 33)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(29, 29, 29)
                                .addComponent(jCheckBox_EsPropietario)
                                .addGap(132, 132, 132)
                                .addComponent(jLabel28)
                                .addGap(26, 26, 26)
                                .addComponent(jComboBox_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_añadirZona)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_nombreComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboBox_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirRubro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_añadirDireccionComercio)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jCheckBox_habilitarDireccionComercio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jCheckBox_EsPropietario)
                    .addComponent(jLabel28)
                    .addComponent(jComboBox_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_añadirZona, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jTextField_referenciaComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41.setText("Buscar Cliente");

        jTextField_buscarCliente.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_buscarClienteCaretUpdate(evt);
            }
        });
        jTextField_buscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_buscarClienteKeyTyped(evt);
            }
        });

        rbtn_clientesDni.setText("DNI");
        rbtn_clientesDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_clientesDniActionPerformed(evt);
            }
        });

        rbtn_clientesNombre.setText("Nombre");

        tabla_clientes_busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_clientes_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_clientes_busquedaMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabla_clientes_busqueda);

        btn_proveedores_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_eliminar.setText("Eliminar");
        btn_proveedores_eliminar.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_eliminar.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_eliminar.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_eliminarMouseClicked(evt);
            }
        });
        btn_proveedores_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedores_eliminarActionPerformed(evt);
            }
        });

        btn_proveedores_modificar.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_modificar.setText("Modificar");
        btn_proveedores_modificar.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_modificar.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_modificar.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_modificarMouseClicked(evt);
            }
        });
        btn_proveedores_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedores_modificarActionPerformed(evt);
            }
        });

        btn_proveedores_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo.setText("Nueva solicitud");
        btn_proveedores_nuevo.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevoMouseClicked(evt);
            }
        });
        btn_proveedores_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedores_nuevoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setText("DNI");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Conyugue");

        jLabel4.setText("Solicitud Numero:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        btn_proveedores_nuevo1.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo1.setText("Ver Solicitudes");
        btn_proveedores_nuevo1.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo1.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo1.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevo1MouseClicked(evt);
            }
        });
        btn_proveedores_nuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedores_nuevo1ActionPerformed(evt);
            }
        });

        btn_proveedores_nuevo2.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo2.setText("Cargar Relacion");
        btn_proveedores_nuevo2.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo2.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo2.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevo2MouseClicked(evt);
            }
        });

        btn_proveedores_nuevo3.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo3.setText("Nuevo");
        btn_proveedores_nuevo3.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo3.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo3.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevo3MouseClicked(evt);
            }
        });

        btn_proveedores_nuevo4.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo4.setText("Imprimir");
        btn_proveedores_nuevo4.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo4.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo4.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevo4MouseClicked(evt);
            }
        });

        btn_proveedores_nuevo5.setBackground(new java.awt.Color(255, 255, 255));
        btn_proveedores_nuevo5.setText("Cancelar");
        btn_proveedores_nuevo5.setMaximumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo5.setMinimumSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo5.setPreferredSize(new java.awt.Dimension(133, 39));
        btn_proveedores_nuevo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_proveedores_nuevo5MouseClicked(evt);
            }
        });

        jLabel9.setText("Total de creditos solicitados por el Titular y el Conyuge:");

        jLabel10.setText("label???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_proveedores_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtn_clientesDni)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtn_clientesNombre))
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextField2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(69, 69, 69)
                                        .addComponent(jTextField3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextField4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_proveedores_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(btn_proveedores_nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 40, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))))
                            .addComponent(jTextField_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_proveedores_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_proveedores_nuevo3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_proveedores_nuevo4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_proveedores_nuevo5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_proveedores_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(690, 690, 690))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_clientesDni)
                            .addComponent(rbtn_clientesNombre)
                            .addComponent(jLabel5)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_proveedores_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_proveedores_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores_nuevo4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_rubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_rubroActionPerformed
        // TODO add your handling code here:
        jButton_añadirRubro.setEnabled(true);
    }//GEN-LAST:event_jComboBox_rubroActionPerformed

    private void jTextField_nombreComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreComercioActionPerformed

    private void jTextField_referenciaComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_referenciaComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_referenciaComercioActionPerformed

    private void jButton_añadirRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirRubroActionPerformed
        // TODO add your handling code here:
        jDialogAñadirElemento.setVisible(true);
        jDialogAñadirElemento.setModal(true);
        jDialogAñadirElemento.setLocationRelativeTo(this);
        jDialogAñadirElemento.setSize(400,221);
        jDialogAñadirElemento.setTitle("Añadir un nuevo Rubro");
    }//GEN-LAST:event_jButton_añadirRubroActionPerformed

    private void btn_añadirDireccionComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirDireccionComercioActionPerformed
        // TODO add your handling code here:
        jDialogClienteCargarDireccion.setVisible(true);
        jDialogClienteCargarDireccion.setModal(true);
        jDialogClienteCargarDireccion.setLocationRelativeTo(this);
        //jDialogClienteCargarDireccion.setSize(400,221);
        jDialogClienteCargarDireccion.setTitle("Añadir la direccion del comercio");
    }//GEN-LAST:event_btn_añadirDireccionComercioActionPerformed

    private void jCheckBox_habilitarDireccionComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_habilitarDireccionComercioActionPerformed
        btn_añadirDireccionComercio.setEnabled(true);
    }//GEN-LAST:event_jCheckBox_habilitarDireccionComercioActionPerformed

    private void jTextField_buscarClienteCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_buscarClienteCaretUpdate
        cambioBusqueda(jTextField_buscarCliente.getText().toString(), rbtn_clientesDni.isSelected(),rbtn_clientesNombre.isSelected(),jTextField_buscarCliente,tabla_clientes_busqueda);
    }//GEN-LAST:event_jTextField_buscarClienteCaretUpdate

    private void jTextField_buscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_buscarClienteKeyTyped

        char c = evt.getKeyChar();
        if (this.rbtn_clientesDni.isSelected()) {
            if ((c < '0' || c > '9')) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_jTextField_buscarClienteKeyTyped

    private void tabla_clientes_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clientes_busquedaMouseClicked
        int pos = tabla_clientes_busqueda.getSelectedRow();
        if (pos != -1) {
            cargarDatosProveedor(pos);
        }
    }//GEN-LAST:event_tabla_clientes_busquedaMouseClicked

    private void btn_proveedores_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_eliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_eliminarMouseClicked

    private void btn_proveedores_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedores_eliminarActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "ELIMINAR", "Esta seguro que desea eliminar el proveedor: \n"+proveedor_selected.getNombre(),JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(result == JOptionPane.OK_OPTION){
            if(proveedoresDAO.eliminarProveedor(proveedor_selected) > 0){
                principal.lbl_estado.setText("El proveedor se elimino con exito");
                principal.lbl_estado.setForeground(Color.GREEN);
            }else{
                principal.lbl_estado.setText("Hubo un error al eliminar el proveedor");
                principal.lbl_estado.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_btn_proveedores_eliminarActionPerformed

    private void btn_proveedores_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_modificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_modificarMouseClicked

    private void btn_proveedores_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedores_modificarActionPerformed
        if(proveedor_selected != null){
            modificarTrue = true;
            habilitarCampos(true);
            cargarNacionalidades();
        }

    }//GEN-LAST:event_btn_proveedores_modificarActionPerformed

    private void btn_proveedores_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevoMouseClicked

    private void btn_proveedores_nuevo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo1MouseClicked

    private void btn_proveedores_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevoActionPerformed

    private void btn_proveedores_nuevo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo2MouseClicked

    private void btn_proveedores_nuevo3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo3MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btn_proveedores_nuevo4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo4MouseClicked

    private void btn_proveedores_nuevo5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo5MouseClicked

    private void btn_proveedores_nuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedores_nuevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_proveedores_nuevo1ActionPerformed

    private void jComboBox_zonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_zonasActionPerformed
        // TODO add your handling code here:
        jButton_añadirZona.setEnabled(true);

    }//GEN-LAST:event_jComboBox_zonasActionPerformed

    private void jButton_añadirZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirZonaActionPerformed
        // TODO add your handling code here:
        jDialogAñadirElemento.setVisible(true);
        jDialogAñadirElemento.setModal(true);
        jDialogAñadirElemento.setLocationRelativeTo(this);
        jDialogAñadirElemento.setSize(400,221);
        jDialogAñadirElemento.setTitle("Añadir una nueva Zona");
    }//GEN-LAST:event_jButton_añadirZonaActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButtonAñadirBarrio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirBarrio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAñadirBarrio2ActionPerformed

    private void jButton_añadirCiudad_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirCiudad_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirCiudad_jDialogActionPerformed

    private void jButton_añadirCalles_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirCalles_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirCalles_jDialogActionPerformed

    private void jTextField_codPostal_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codPostal_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codPostal_jDialogActionPerformed

    private void jButton_añadirProvincia_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadirProvincia_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadirProvincia_jDialogActionPerformed

    private void jTextField_numeroDireccion_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_numeroDireccion_jDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_numeroDireccion_jDialogActionPerformed

    private void jTextField_numeroDireccion_jDialogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_numeroDireccion_jDialogKeyTyped
        // TODO add your handling code here:
        jButton_ok.setEnabled(true);
    }//GEN-LAST:event_jTextField_numeroDireccion_jDialogKeyTyped

    private void jComboBox_direccion_jDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_direccion_jDialogActionPerformed
        // TODO add your handling code here:
        jTextField_numeroDireccion_jDialog.setEnabled(true);
    }//GEN-LAST:event_jComboBox_direccion_jDialogActionPerformed

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // TODO add your handling code here:
        //At the end of all controls, it enables the flag of the commerce address;

        if(Funciones.compareStrings("-",String.valueOf(jComboBox_provincia_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null,"Debe ingresar una provincia valida","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Funciones.compareStrings("-", String.valueOf(jComboBox_Ciudad_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null,"Debe ingresar una ciudad validad","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Funciones.compareStrings("-",String.valueOf(jComboBox_direccion_jDialog.getSelectedItem()))){
            JOptionPane.showMessageDialog(null, "Debe ingresar una direccion valida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!Funciones.isNumeric(jTextField_numeroDireccion_jDialog.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar un numero de direccion","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!Funciones.isNumeric(jTextField_codPostal_jDialog.getText())){
            JOptionPane.showMessageDialog(null,"Debe ingresar un codigo postal","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_jButton_okActionPerformed

    private void jTextF_IngresarNuevoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextF_IngresarNuevoElementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextF_IngresarNuevoElementoActionPerformed

    private void btn_añadirNuevoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirNuevoElementoActionPerformed
        String textoInput= jTextF_IngresarNuevoElemento.getText().toLowerCase();
        switch(jDialogAñadirElemento.getTitle()){
            case "Añadir una nueva Nacionalidad":{
                direccionesDAO.añadirNacionalidad(textoInput);
                jCombo_Naciones.addItem(textoInput);
                jCombo_Naciones.setSelectedItem(textoInput);
                break;
            }
            case "Añadir una nueva Provincia":{
                direccionesDAO.añadirProvincia(textoInput);
                jComboBox_Provincias.addItem(textoInput);
                jComboBox_Provincias.setSelectedItem(textoInput);
            }
            case "Añadir una nueva Ciudad":{
                direccionesDAO.añadirCiudad(textoInput);
                jComboBox_Ciudades.addItem(textoInput);
                jComboBox_Ciudades.setSelectedItem(textoInput);
                break;
            }
            case "Añadir un nuevo Barrio":{
                direccionesDAO.añadirBarrio(textoInput);
                jComboBox_Barrios.addItem(textoInput);
                jComboBox_Barrios.setSelectedItem(textoInput);
                break;
            }
            case "Añadir una nueva Calle/Manzana":{
                direccionesDAO.añadirDireccion(textoInput);
                jComboBox_calles.addItem(textoInput);
                jComboBox_calles.setSelectedItem(textoInput);
                break;
            }
            case "Añadir un nuevo tipo de contacto":{
                //quizas necesite un contactosDAO
            }
            case "Añadir una nueva Zona":{
                //quizas necesite un zonaDAO
            }
        }
    }//GEN-LAST:event_btn_añadirNuevoElementoActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void rbtn_clientesDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_clientesDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn_clientesDniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadirDireccionComercio;
    private javax.swing.JButton btn_añadirNuevoElemento;
    private javax.swing.JButton btn_proveedores_eliminar;
    private javax.swing.JButton btn_proveedores_modificar;
    private javax.swing.JButton btn_proveedores_nuevo;
    private javax.swing.JButton btn_proveedores_nuevo1;
    private javax.swing.JButton btn_proveedores_nuevo2;
    private javax.swing.JButton btn_proveedores_nuevo3;
    private javax.swing.JButton btn_proveedores_nuevo4;
    private javax.swing.JButton btn_proveedores_nuevo5;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAñadirBarrio2;
    private javax.swing.JButton jButton_añadirCalle_jDialog;
    private javax.swing.JButton jButton_añadirCalles_jDialog;
    private javax.swing.JButton jButton_añadirCiudad_jDialog;
    private javax.swing.JButton jButton_añadirProvincia_jDialog;
    private javax.swing.JButton jButton_añadirRubro;
    private javax.swing.JButton jButton_añadirZona;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JCheckBox jCheckBox_EsPropietario;
    private javax.swing.JCheckBox jCheckBox_habilitarDireccionComercio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox_Ciudad_jDialog;
    private javax.swing.JComboBox<String> jComboBox_barrio_JDialog;
    private javax.swing.JComboBox<String> jComboBox_direccion_jDialog;
    private javax.swing.JComboBox<String> jComboBox_provincia_jDialog;
    private javax.swing.JComboBox<String> jComboBox_rubro;
    private javax.swing.JComboBox<String> jComboBox_zonas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialogAñadirElemento;
    private javax.swing.JDialog jDialogClienteCargarDireccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTextField jTextF_IngresarNuevoElemento;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    protected javax.swing.JTextField jTextField_buscarCliente;
    private javax.swing.JTextField jTextField_codPostal_jDialog;
    private javax.swing.JTextField jTextField_nombreComercio;
    private javax.swing.JTextField jTextField_numeroDireccion_jDialog;
    private javax.swing.JTextField jTextField_referenciaComercio;
    private javax.swing.JTextField jTextField_referencia_jDialog;
    protected javax.swing.JRadioButton rbtn_clientesDni;
    protected javax.swing.JRadioButton rbtn_clientesNombre;
    private javax.swing.JTable tabla_clientes_busqueda;
    // End of variables declaration//GEN-END:variables
//panel buscador
    public void cambioBusqueda(String txt,boolean codigo, boolean nombre, JTextField buscador, JTable tablaBuscador){
            
        if(txt.isEmpty()){
            cargarTablaBusqueda(proveedoresDAO.buscarProveedor("nombre",""),tablaBuscador);
        }else if(codigo){
            try{
                int cod = Integer.parseInt(txt);
                cargarTablaBusqueda(proveedoresDAO.buscarProveedor(cod),tablaBuscador);
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,"Debe ingresar un código", 
                    "Error",  JOptionPane.ERROR_MESSAGE);
                buscador.setText("");
            }
        }else if(nombre){
            cargarTablaBusqueda(proveedoresDAO.buscarProveedor("nombre", txt.toLowerCase()),tablaBuscador);
        }else{
            System.out.println("Error no selecciono tipo de busqueda");
        }
    }
    public void cargarTablaBusqueda(List<Proveedor> prov, JTable tablaBuscador){
        lista_proveedores = new ArrayList<>(prov);
        DefaultTableModel model = (DefaultTableModel) tablaBuscador.getModel();
        model.setNumRows(0);
         try {
            Object[] obj = new Object[2];
            for (int i = 0; i < lista_proveedores.size(); i++) {
                obj[0] = lista_proveedores.get(i).getId();
                obj[1] = lista_proveedores.get(i).getNombre();
                model.addRow(obj);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    public void cargarDatosProveedor(int pos){
        if (pos != -1) {
            proveedor_selected = lista_proveedores.get(pos);
            txtf_nombre_empresa.setText(proveedor_selected.getNombre());
            txtf_observaciones.setText(proveedor_selected.getObservaciones());
            txtf_cbu.setText(proveedor_selected.getCbu());
            txtf_cuit.setText(proveedor_selected.getCuit());
            cbox_barrio.removeAllItems();
            cbox_barrio.addItem(proveedor_selected.getIva());
            //contacto
            txtf_contacto.setText("");
            //direccion
            txtf_codigoPostal.setText(proveedor_selected.getCodigoPostal());
            txtf_nro.setText(proveedor_selected.getNro());
        }
    }
}
