/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Statics.*;
import javax.swing.ImageIcon;
/**
 *
 * @author demig
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        nombre_usuario.setText("Usuario: "+Main.logueado.getUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        barra_estado = new javax.swing.JPanel();
        lbl_estado = new javax.swing.JLabel();
        nombre_usuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(1200, 704));
        setMinimumSize(new java.awt.Dimension(1200, 704));
        setPreferredSize(new java.awt.Dimension(1366, 900));
        setSize(new java.awt.Dimension(1366, 900));
        getContentPane().setLayout(null);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1360, 680));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1360, 680));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1360, 680));
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1360, 680);
        jTabbedPane1.add(new Views.ProductosView());
        jTabbedPane1.add(new Views.ABMClientesView());
        jTabbedPane1.add(new Views.ProveedoresView());
        jTabbedPane1.add(new Views.Facturacion());
        jTabbedPane1.add(new Views.Auxiliar());
        jTabbedPane1.add(new Views.AltaUsuariosView());
        jTabbedPane1.add(new Views.GenerarRemito());
        jTabbedPane1.add(new Views.ControlRemitos());
        jTabbedPane1.setIconAt(0, new ImageIcon(getClass().getResource("/Statics/productos.png")));
        jTabbedPane1.setIconAt(1, new ImageIcon(getClass().getResource("/Statics/clientes.png")));
        jTabbedPane1.setIconAt(2, new ImageIcon(getClass().getResource("/Statics/proveedores.png")));
        jTabbedPane1.setIconAt(3, new ImageIcon(getClass().getResource("/Statics/facturacion.png")));
        jTabbedPane1.setIconAt(4, new ImageIcon(getClass().getResource("/Statics/auxiliar.png")));
        jTabbedPane1.setIconAt(5, new ImageIcon(getClass().getResource("/Statics/usuarios.png")));
        jTabbedPane1.setIconAt(5, new ImageIcon(getClass().getResource("/Statics/usuarios.png")));
        jTabbedPane1.setIconAt(5, new ImageIcon(getClass().getResource("/Statics/usuarios.png")));

        barra_estado.setBackground(new java.awt.Color(238, 238, 238));
        barra_estado.setMaximumSize(new java.awt.Dimension(1360, 25));
        barra_estado.setMinimumSize(new java.awt.Dimension(1360, 25));
        barra_estado.setPreferredSize(new java.awt.Dimension(1360, 25));

        nombre_usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nombre_usuario.setText("Usuario:");

        javax.swing.GroupLayout barra_estadoLayout = new javax.swing.GroupLayout(barra_estado);
        barra_estado.setLayout(barra_estadoLayout);
        barra_estadoLayout.setHorizontalGroup(
            barra_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_estadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_estado, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addGap(299, 299, 299)
                .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barra_estadoLayout.setVerticalGroup(
            barra_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_estadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nombre_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbl_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        barra_estadoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbl_estado, nombre_usuario});

        getContentPane().add(barra_estado);
        barra_estado.setBounds(0, 680, 1360, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_estado;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel nombre_usuario;
    // End of variables declaration//GEN-END:variables
}
