/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Inicio;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author jerem
 */
public class DigitalClock extends javax.swing.JPanel {

    /**
     * Creates new form DigitalClock
     */
    public DigitalClock() {
        initComponents();
        ClockLabel dateLable = new ClockLabel("date");
        ClockLabel timeLable = new ClockLabel("time");
        ClockLabel dayLable = new ClockLabel("day");
        this.setSize(300,150);
        this.setLayout(new GridLayout(3, 1));
        this.add(dateLable);
        this.add(timeLable);
        this.add(dayLable);
        this.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
     
    class ClockLabel extends JLabel implements ActionListener {
 
    String type;
    SimpleDateFormat sdf;

    public ClockLabel(String type) {
      this.type = type;
      setForeground(Color.BLACK);

      switch (type) {
        case "date" : sdf = new SimpleDateFormat("  MMMM dd yyyy");
                      setFont(new Font("sans-serif", Font.PLAIN, 12));
                      setHorizontalAlignment(SwingConstants.LEFT);
                      break;
        case "time" : sdf = new SimpleDateFormat("hh:mm:ss a");
                      setFont(new Font("sans-serif", Font.PLAIN, 40));
                      setHorizontalAlignment(SwingConstants.CENTER);
                      break;
        case "day"  : sdf = new SimpleDateFormat("EEEE  ");
                      setFont(new Font("sans-serif", Font.PLAIN, 16));
                      setHorizontalAlignment(SwingConstants.RIGHT);
                      break;
        default     : sdf = new SimpleDateFormat();
                      break;
      }

      Timer t = new Timer(1000, this);
      t.start();
    }

    public void actionPerformed(ActionEvent ae) {
      Date d = new Date();
      setText(sdf.format(d));
    }

  }
}
